name: Deploy to mu labda functions

on:
  push:
    branches:
      - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: checkout code
       uses: actions/checkout@v2
     - name: set up python
       uses: actions/setup-python@v2
       with:
         python-version: 3.8 
     - name: Install libraries 
       run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirments.txt -t .; fi
     - name: Create a zip bundel
       run: |
           cd function
           zip -r ../${{ github.sha }}.zip .
     - name: Archive artifact
       uses: actions/upload-artifact@v2
       with:
          name: zipped-bundel
          path: ${{ github.sha }}.zip
          
