name: Deploy to mu labda functions

on:
  push:
    branches:
      - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: checkout code
       uses: actions/checkout@v3
     - name: set up python
       uses: actions/setup-python@v4
       with:
         python-version: 3.8 
     - name: Install libraries 
       run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
     - name: Create a zip bundel
       run: |
           cd function
           zip -r ../${{ github.sha }}.zip .
     - name: Archive artifact
       uses: actions/upload-artifact@v3
       with:
          name: zipped-bundel
          path: ${{ github.sha }}.zip
 upload:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: zipped-bundel
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - name: Upload to S3
          run: aws s3 cp ${{ github.sha }}.zip s3://my-zodak-buck/${{ github.repository }}/${{ github.sha }}.zip

 deploy:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Update function code
        run: |
            aws lambda update-function-code \
              --function-name my-functions \
              --s3-bucket my-zodak-buck \
              --s3-key ${{ github.repository }}/${{ github.sha }}.zip \
              --publish
